[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "aoc"
version = "0.1dev"
authors = [
  { name="Nicolas Appriou", email="nicolas.appriou@gmail.com" }
]
description = "A framework for the Advent of Code yearly challenge"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "click ~= 8.1",
]

[project.scripts]
aoc = "aoc.cli:cli"

[project.optional-dependencies]
dev = [
  "mypy ~= 0.991",
  "pytest ~= 7.2",
]

[project.urls]
Homepage = "https://github.com/Nicals/aoc"

[tool.setuptools]
packages = ["aoc"]

[tool.mypy]
packages = ["aoc"]
